version: "3.7"
#name: team_services
services:
  team_api:
    build: .
    image: team_api_image
    container_name: team_api_container
    ports:
      - "8001:8000"
    links:
      - team_postgres_app
    env_file:
      - .env
    volumes:
      - type: bind
        source: .
        target: /usr/src/app
      - /usr/src/app/node_modules

  team_postgres_app:
    image: postgres:alpine
    container_name: team_postgres_container
    ports:
      - "5432:5432"
    env_file:
    - .env.db.docker
    volumes:
    - team_postgres:/var/lib/postgresql/data

volumes:
  team_postgres:
